apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: sorydiallo89/gitops-pipeline-argocd-kubernetes:1.0.0-20
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
